config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :emps

  resources :documents
  
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :emp

  has_one_attached :image

  validates :name, :doc_type, presence: true
end

app/models/emp.rb
class Emp < ApplicationRecord
    has_many :documents

    validates :first_name, :last_name, presence: true
    validates :email, presence: true, uniqueness: true
    validates :phone, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
    def index
        @documents = Document.all        
    end

    def new 
        @document = Document.new
    end

    def create
        @document = Document.new(document_params)
        if @document.save
            redirect_to documents_path, notice: "Documents has been created successfully"
        else
            render :new
        end
    end

    def edit
        @document = Document.find(params[:id])
    end

    def update
        @document = Document.find(params[:id])
        if @document.update(document_params)
            redirect_to documents_path, notice: 'Documents has been Updated successfully'  
        else
            reder :edit
        end
    end

    def show
        @document = Document.find(params[:id])

    end
  
    def destroy
        @document = Document.find(params[:id])
        if @document.destroy
            redirect_to documents_path, notice: 'Document has been deleted successfully'
        end
    end

    private

    def document_params
        params.require(:document).permit(:name, :doc_type, :emp_id, :image)
    end
end

app/controllers/emps_controller.rb
class EmpsController < ApplicationController
    def index
    @emps = Emp.all
    end

    def new
        @emp = Emp.new 
    end

    def create
        @emp = Emp.new(emp_params)
        if @emp.save
            redirect_to emps_path, notice: 'Employee has been created successfully'
        else
            render :new
        end 
    end

    def edit
        @emp = Emp.find(params[:id])

    end

    def update
        @emp = Emp.find(params[:id])
        if @emp.update(emp_params)
            redirect_to emps_path, notice: 'Employee has been Updated successfully'  
        else
            reder :edit
        end
    end

    def show
        @emp = Emp.find(params[:id])

    end

    def destroy
        @emp = Emp.find(params[:id])
        if @emp.destroy
            redirect_to emps_path, notice: 'Employee has been deleted successfully'
        end
    end

    private 

    def emp_params
        params.require(:emp).permit(:first_name, :middle_name, :last_name, :email, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/documents/edit.html.erb
<div class="col-lg-12">

    <div class="container card mt-5 mb-5">
        <div class="card-body">
            <h2 class="text-center"> Edit Document </h2>
        </div>
    </div>

    <%= form_with model: @document do |form| %>
    <div class="row container">
        <div class="col-lg-4">
            <div class="form-group">
                <%= form.label :name, class: 'mb-2' %>
                <%= form.text_field :name, class: 'form-control form-control-lg'%>
            </div>
            <div class="form-group">
                <%= form.label :doc_type, class: 'mb-2' %>
                <%= form.text_field :doc_type, class: 'form-control form-control-lg'%>
            </div>
            <div class="form-group">
                <%= form.label :emp_id, class: 'mb-2' %>
                <%= form.number_field :emp_id, class: 'form-control form-control-lg'%>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12 m-5">
                <%= form.submit class: 'btn btn-primary' %>
                <%= link_to "Back to Document", documents_path, class: "btn btn-outline-primary" %>
            </div>
        </div>
    </div>
    <% end %>




</div>

app/views/documents/index.html.erb
<%= flash[:notice] %>
<div class="container card mt-5 mb-5">
    <div class="card-body">
        <h2 class="text-center"> Listing Employee Documents </h2>

    </div>
</div>

<div class="container">
    <%= link_to "Create new Document", new_document_path, class:" btn btn-primary mb-4 "%>
</div>
<table class="container table table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Document type</th>
            <th>Employee ID</th>

        </tr>
    </thead>
    <tbody>
        <% @documents.each do |document| %>
            <tr>
                <td><%= document.name %></td>
                <td><%= document.doc_type %></td>
                <td><%= document.emp.first_name %></td>
                <td>
                    <%= link_to "Edit", edit_document_path(document), class: "btn btn-primary" %>
                    <%= link_to "View", document_path(document), class: "btn btn-info" %>
                    <%= link_to "Delete", document_path(document), class: "btn btn-danger", method: :delete, data: {confirm: 'Are you sure to delete this document'} %>
                </td>
            </tr>
        <% end %>

    </tbody>
</table>

app/views/documents/new.html.erb
<div class="col-lg-12">

    <div class="container card mt-5 mb-5">
        <div class="card-body">
            <h2 class="text-center"> Create New Document </h2>
        </div>
    </div>

    <%= form_with model: @document do |form| %>
    <div class="row container">
        <div class="col-lg-4">
            <div class="form-group">
                <%= form.label :name, class: 'mb-2' %>
                <%= form.text_field :name, class: 'form-control form-control-lg'%>
            </div>
            <div class="form-group">
                <%= form.label :doc_type, class: 'mb-2' %>
                <%= form.text_field :doc_type, class: 'form-control form-control-lg'%>
            </div>
            <div class="form-group">
                <%= form.label :emp_id, class: 'mb-2' %>
                <%= form.number_field :emp_id, class: 'form-control form-control-lg'%>
            </div>

            <div class="form-group">
                <%= form.label :image, class: 'mb-2' %><br>
                <%= form.file_field :image%>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12 m-5">
                <%= form.submit class: 'btn btn-primary' %>
                <%= link_to "Back to Document", documents_path, class: "btn btn-outline-primary" %>
            </div>
        </div>
    </div>
    <% end %>




</div>

app/views/documents/show.html.erb
<div class="col-lg-12">
    <div class="container card mt-5 mb-5">
        <div class="card-body">
            <h2 class="text-center"> Document Details</h2>
            <div class="row">
                <div class="col-lg-6">
                    <%# <h3 class="text-center">Personal Information</h3> %>
                    <% if @document.image.attached? %>
                        <%= image_tag @document.image %>
                    <% end %>
                    <p class="lead"><strong> Name :</strong> <%= @document.name%></p>
                    <p class="lead"><strong> Document type  :</strong> <%= @document.doc_type %></p>
                </div>
            </div>

            <%= link_to "Back to Documents", documents_path, class: "btn btn-outline-primary"%>
            <%= link_to "Edit Document", edit_document_path(@document), class: "btn btn-primary"%>

        </div>
    </div>
</div>

app/views/emps/edit.html.erb
<div class="col-lg-12">
    <div class="container card mt-5 mb-5">
        <div class="card-body">
            <h2 class="text-center"> Edit Employee Information</h2>
        </div>
    </div>

    <%= form_with model: @emp do |form| %>
        <div class="row container">
            <div class="col-lg-4">
                <div class="form-group">
                    <%= form.label :first_name, class: 'mb-2' %>
                    <%= form.text_field :first_name, class: 'form-control form-control-lg'%>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="form-group">
                    <%= form.label :middle_name, class: 'mb-2' %>
                    <%= form.text_field :middle_name, class: 'form-control form-control-lg'%>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="form-group">
                    <%= form.label :last_name, class: 'mb-2' %>
                    <%= form.text_field :last_name, class: 'form-control form-control-lg'%>
                </div>
            </div>


            <div class="col-lg-4">
                <div class="form-group">
                    <%= form.label :email, class: 'mb-2' %>
                    <%= form.text_field :email, class: 'form-control form-control-lg'%>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="form-group">
                    <%= form.label :phone, class: 'mb-2' %>
                    <%= form.text_field :phone, class: 'form-control form-control-lg'%>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12 m-5">
                <%= form.submit class: 'btn btn-primary' %>
                <%= link_to "Back to Employee", emps_path, class: "btn btn-outline-primary" %>
            </div>
        </div>
    <% end %>
</div>

app/views/emps/index.html.erb
<%= flash[:notice] %>
<div class="container card mt-5 mb-5">
    <div class="card-body">
        <h2 class="text-center"> Listing Employee </h2>
    </div>
</div>

<div class="container">
    <%= link_to "Create new Employee", new_emp_path, class:" btn btn-primary mb-4 "%>
</div>
<table class="container table table-bordered">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Middle Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Actions</th>

        </tr>
    </thead>
    <tbody>
        <% @emps.each do |emp| %>
            <tr>
                <td><%= emp.first_name %></td>
                <td><%= emp.middle_name %></td>
                <td><%= emp.last_name %></td>
                <td><%= emp.email %></td>
                <td><%= emp.phone %></td>
                <td>
                    <%= link_to "Edit", edit_emp_path(emp), class: "btn btn-primary" %>
                    <%= link_to "View", emp_path(emp), class: "btn btn-info" %>
                
                    <%= link_to "Delete", emp_path(emp), class: "btn btn-danger", method: :delete, data: {confirm: 'Are you sure to delete this employee'} %>
                </td>
            </tr>
        <% end %>

    </tbody>
</table>

app/views/emps/new.html.erb
<div class="col-lg-12">
    <div class="container card mt-5 mb-5">
        <div class="card-body">
            <h2 class="text-center"> Create New Employee </h2>
        </div>
    </div>

    <%= form_with model: @emp do |form| %>
        <div class="row container">
            <div class="col-lg-4">
                <div class="form-group">
                    <%= form.label :first_name, class: 'mb-2' %>
                    <%= form.text_field :first_name, class: 'form-control form-control-lg'%>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="form-group">
                    <%= form.label :middle_name, class: 'mb-2' %>
                    <%= form.text_field :middle_name, class: 'form-control form-control-lg'%>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="form-group">
                    <%= form.label :last_name, class: 'mb-2' %>
                    <%= form.text_field :last_name, class: 'form-control form-control-lg'%>
                </div>
            </div>


            <div class="col-lg-4">
                <div class="form-group">
                    <%= form.label :email, class: 'mb-2' %>
                    <%= form.text_field :email, class: 'form-control form-control-lg'%>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="form-group">
                    <%= form.label :phone, class: 'mb-2' %>
                    <%= form.text_field :phone, class: 'form-control form-control-lg'%>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12 m-5">
                <%= form.submit class: 'btn btn-primary' %>
                <%= link_to "Back to Employee", emps_path, class: "btn btn-outline-primary" %>
            </div>
        </div>
    <% end %>
</div>

app/views/emps/show.html.erb
<div class="col-lg-12">
    <div class="container card mt-5 mb-5">
        <div class="card-body">
            <h2 class="text-center"> Employee Details</h2>
            <div class="row">
                <div class="col-lg-6">
                    <h3 class="text-center">Personal Information</h3>
                    <p class="lead"><strong> First Name :</strong> <%= @emp.first_name%></p>
                    <p class="lead"><strong> Middle Name :</strong> <%= @emp.middle_name%></p>
                    <p class="lead"><strong> Last Name :</strong> <%= @emp.last_name%></p>
                    <p class="lead"><strong> Email :</strong> <%= @emp.email%></p>
                    <p class="lead"><strong> Phone No :</strong> <%= @emp.phone%></p>
                </div>
            </div>

            <%= link_to "Back to Employees", emps_path, class: "btn btn-outline-primary"%>
            <%= link_to "Edit Employee", edit_emp_path(@emp), class: "btn btn-primary"%>

        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Employee</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <h1>Hello, world!</h1>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>